export default {
  login: "MarcinMysliwiec",
  id: 55953189,
  node_id: "MDQ6VXNlcjU1OTUzMTg5",
  avatar_url: "https://avatars.githubusercontent.com/u/55953189?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/MarcinMysliwiec",
  html_url: "https://github.com/MarcinMysliwiec",
  followers_url: "https://api.github.com/users/MarcinMysliwiec/followers",
  following_url: "https://api.github.com/users/MarcinMysliwiec/following{/other_user}",
  gists_url: "https://api.github.com/users/MarcinMysliwiec/gists{/gist_id}",
  starred_url: "https://api.github.com/users/MarcinMysliwiec/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/MarcinMysliwiec/subscriptions",
  organizations_url: "https://api.github.com/users/MarcinMysliwiec/orgs",
  repos_url: "https://api.github.com/users/MarcinMysliwiec/repos",
  events_url: "https://api.github.com/users/MarcinMysliwiec/events{/privacy}",
  received_events_url: "https://api.github.com/users/MarcinMysliwiec/received_events",
  type: "User",
  site_admin: false,
  name: "Marcin Myśliwiec",
  company: null,
  blog: "mysliw.pl",
  location: "Poland, Poznań",
  email: null,
  hireable: null,
  bio: "Mid-level Javascript and Python developer. Practising and improving my skills :)",
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2019-09-29T15:18:16Z",
  updated_at: "2022-03-18T12:12:55Z"
};

